### ISSUE TITLE
TX bytes are calculated incorrectly when using --binary mode

### ISSUE THREAD

**Issue by bmrzycki** [shaygalon/memcache-perf#3]
Hello,

The following calculation in `Connection::issue_set()` is incorrect for little-endian hosts:
https://github.com/shaygalon/memcache-perf/blob/3c3d5bee2aafe765480f8e727fcfcc2115dd8602/Connection.cc#L270

The value is set to network-byte order (big-endian) earlier in the code:
https://github.com/shaygalon/memcache-perf/blob/3c3d5bee2aafe765480f8e727fcfcc2115dd8602/Connection.cc#L265

The code already handles this for `issue_get_req()` but it looks like it was missed in `issue_set()`. One possible fix is the following code diff:
```
--- Connection.cc.orig	2021-12-07 16:40:55.000000000 -0600
+++ Connection.cc	2021-12-07 16:47:28.000000000 -0600
@@ -259,15 +259,16 @@
     read_state = WAITING_FOR_SET;
 
   if (options.binary) {
+    uint32_t body_len = keylen + 8 + length;
     // each line is 4-bytes
     binary_header_t h = { 0x80, CMD_SET, htons(keylen),
                           0x08, 0x00, {htons(0)}, //TODO(syang0) get actual vbucket?
-                          htonl(keylen + 8 + length)};
+                          htonl(body_len)};
 
     bufferevent_write(bev, &h, 32); // With extras
     bufferevent_write(bev, key, keylen);
     bufferevent_write(bev, value, length);
-    l = 24 + h.body_len;
+    l = 24 + body_len;
   } else {
     l = evbuffer_add_printf(bufferevent_get_output(bev),
                                 "set %s 0 0 %d\r\n", key, length);

```

**Comment by shaygalon** [comment]
Thanks for reporting, fixed.

**Comment by bmrzycki** [comment]
Perfect, thanks Shay!
